version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '**/*.md'
    
before_build:
- cmd: nuget restore src
- ps: |
    $file = 'src\AnyStatus.API\AnyStatus.API.nuspec'
    $xml = [xml](Get-Content $file)
    $xml.package.version = $Env:BUILD_BUILDNUMBER
    $xml.Save($file)

build:
  publish_nuget: true
  verbosity: minimal